config/routes.rb
Rails.application.routes.draw do
  resources :budgets, only: :index do
    resources :budget_balances, only: [:update, :edit], module: :budgets
  end
  resources :transactions, only: [:index, :new, :edit, :create, :update, :destroy]
end

app/models/budget.rb
class Budget
  include ActiveModel::Model

  attr_accessor :current_month

  validates :current_month, presence: true
  validate :current_month_has_to_be_a_date

  def current_month=(value)
    if valid_date?(value)
      @current_month = value.beginning_of_month
    end
  end

  def expense_budget_balances
    collected = []
    Category.where.not(name: Category::INCOME_CATEGORIES).each do |category|
      collected << BudgetBalance.find_or_create_by(category: category, month: current_month)
    end

    collected
  end

  def income_budget_balances
    collected = []
    Category.where(name: Category::INCOME_CATEGORIES).each do |category|
      collected << BudgetBalance.find_or_create_by(category: category, month: current_month)
    end

    collected
  end

  def available_for_budget
    balance = 0

    income_budget_balances.each do |budget_balance|
      balance += budget_balance.balance
    end

    expense_budget_balances.each do |budget_balance|
      balance -= budget_balance.budgeted_balance
    end

    balance
  end

  def add(amount, to:)
    budget_balance = find_budget_balance to
    budget_balance.budgeted = amount
    budget_balance.save
  end

  def move(amount, from:, to:)
    budget_balance_from = find_budget_balance from
    budget_balance_to = find_budget_balance to
    budget_balance_from.budgeted -= amount
    budget_balance_to.budgeted += amount
    budget_balance_from.save
    budget_balance_to.save
  end

  def remove(amount, from:)
    budget_balance = find_budget_balance from
    budget_balance.budgeted -= amount
    budget_balance.save
  end

  def find_budget_balance(category)
    expense_budget_balances.find { |bb| bb.category == category }
  end

  private

  def valid_date?(value)
    value.is_a?(Date)
  end

  def current_month_has_to_be_a_date
    unless valid_date?(current_month)
      errors.add(:current_month, 'is not valid Date')
    end
  end
end

app/controllers/budgets/budget_balances_controller.rb
class Budgets::BudgetBalancesController < ApplicationController
  include Budgetable
  before_action :set_budget, only: :update
  before_action :set_budget_balance, only: :update

  def update
    @budget_balance.update(budget_balance_params)
    respond_to do |format|
      format.js
    end
  end

  private

  def set_budget_balance
    @budget_balance = BudgetBalance.find(params[:id])
  end

  def budget_balance_params
    params.require(:budget_balance).permit(:budgeted)
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  include Budgetable
  before_action :set_budget, only: :index

  def index; end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
  def balance_tag(amount)
    css_class = 'balance_number '
    if amount > 0
      css_class << 'positive'
    elsif amount < 0
      css_class << 'negative'
    end
    if amount.to_i.to_f != amount
      tag.span(class: css_class) {  number_to_currency(amount.round(2), precision: 2) }
    else
      tag.span(class: css_class) {  number_to_currency(amount) }
    end
  end

  def previous_month_link(budget)
    previous_month = budget.current_month - 1.month
    month_pager_link "&larr; #{l(previous_month, format: :year_and_month)}".html_safe, previous_month
  end

  def next_month_link(budget)
    next_month = budget.current_month + 1.month
    month_pager_link "#{l(next_month, format: :year_and_month)} &rarr;".html_safe, next_month
  end

  def month_pager_link(text, month)
    link_to text, budgets_path(current_month: month)
  end
end

app/views/budgets/_available_for_budget.html.erb
<th id="available_for_budget" colspan="4">
  <%= t('budget.messages.available_for_budget') %>:
  <%= balance_tag budget.available_for_budget %>
</th>

app/views/budgets/index.html.erb
<div class="grid">
  <div class="unit content_body">
    <header class="grid record_table_title">
      <div class="unit section_title_container">
        <h1 class="section_title"><%= t('budget.titles.index') %></h1>
      </div>
      <div class="unit record_table_title_actions">
        <ul class="horizontal plain button_panel">
          <li><%= link_to t('transaction.actions.index'), transactions_path, class: 'button secondary' %></li>
          <li><%= link_to t('transaction.actions.new'), new_transaction_path, class: 'button' %></li>
        </ul>
      </div>
    </header>

    <header class="month_pager">
      <ul class="horizontal plain">
        <li><%= previous_month_link(@budget) %></li>
        <li><%= l @budget.current_month, format: :year_and_month %></li>
        <li><%= next_month_link(@budget) %></li>
      </ul>
    </header>

    <div class="record_table_wrapper">
      <table class="record_table">
        <thead>
          <tr>
            <%= render 'available_for_budget', budget: @budget %>
          </tr>
          <tr>
            <th><%= column_title :budget_balance, :category %></th>
            <th class="text_right"><%= column_title :budget_balance, :budgeted %></th>
            <th class="text_right"><%= column_title :budget_balance, :spent %></th>
            <th class="text_right"><%= column_title :budget_balance, :balance %></th>
          </tr>
        </thead>
        <tbody>
          <% @budget.expense_budget_balances.each do |expense_budget| %>
            <%= render 'budgets/budget_balances/budget_balance', budget_balance: expense_budget %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>