config/routes.rb
Rails.application.routes.draw do
  resources :budgets, only: :index do
    resources :budget_balances, only: [:update, :edit], module: :budgets
  end
  resources :transactions, only: [:index, :new, :edit, :create, :update, :destroy]
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  def index
    @transactions = Transaction.all

    respond_to do |format|
      format.html
    end
  end

  def show; end

  def new
    @transaction = Transaction.new
  end

  def edit; end

  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to budgets_path, notice: record_notice(@transaction, action: __method__.to_s) }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to budgets_path, notice: record_notice(@transaction, action: __method__.to_s) }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_path, notice: record_notice(@transaction, action: __method__.to_s) }
    end
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:account_id, :category_id, :payee, :amount)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(transaction) do |f| %>
  <% if transaction.errors.any? %>
    <%= render 'application/error_explanation', model: transaction %>
  <% end %>

  <div class="form_field inline">
    <div class="field_label right">
      <%= f.label :account_id %>
    </div>
    <div class="field_input">
      <%= f.collection_select :account_id, Account.all, :id, :name %>
    </div>
  </div>

  <div class="form_field inline">
    <div class="field_label right">
      <%= f.label :category_id %>
    </div>
    <div class="field_input">
      <%= f.collection_select :category_id, Category.by_name, :id, :name, include_blank: true %>
    </div>
  </div>

  <div class="form_field inline">
    <div class="field_label right">
      <%= f.label :payee %>
    </div>
    <div class="field_input">
      <%= f.text_field :payee %>
    </div>
  </div>

  <div class="form_field inline">
    <div class="field_label right">
      <%= f.label :amount %>
    </div>
    <div class="field_input">
      <%= f.number_field :amount %>
    </div>
  </div>

  <%= form_actions inline: true do %>
    <%= f.submit @transaction.new_record? ? t('transaction.actions.create') : t('transaction.actions.update'), class: 'button' %>
    <%= link_to t('shared.actions.cancel'), budgets_path, class: 'cancel_button' %>
  <% end %>
<% end %>

app/views/transactions/_transaction.html.erb
<%= tag.tr id: dom_id(transaction), class: 'transaction' do %>
  <td><%= l transaction.created_at, format: :short %></td>
  <td><%= transaction.category.name %></td>
  <td><%= transaction.account.name %></td>
  <td><%= transaction.payee %></td>
  <td class="text_right"><%= transaction.amount %></td>
  <td>
    <ul class="record_table_actions">
      <li>
        <%= link_to t('shared.actions.edit'), edit_transaction_path(transaction), class: 'edit_button' %>
      </li>
      <li>
        <%= link_to t('shared.actions.destroy'), transaction, method: :delete,
              data: { confirm: t("transaction.confirmations.destroy") },
              class: 'destroy_button' %>
      </li>
    </ul>
  </td>
<% end %>

app/views/transactions/edit.html.erb
<div class="grid">
  <div class="unit content_body">
    <header class="grid record_table_title">
      <div class="unit section_title_container">
        <h1 class="section_title"><%= t('transaction.titles.edit') %></h1>
      </div>
    </header>
    <%= render 'form', transaction: @transaction %>
  </div>
</div>

app/views/transactions/index.html.erb
<div class="grid">
  <div class="unit content_body">
    <header class="grid record_table_title">
      <div class="unit section_title_container">
        <h1 class="section_title"><%= t('transaction.titles.index') %></h1>
      </div>
      <div class="unit record_table_title_actions">
        <ul class="horizontal plain button_panel">
          <li><%= link_to t('budget.actions.index'), budgets_path, class: 'button secondary' %></li>
          <li><%= link_to t('transaction.actions.new'), new_transaction_path, class: 'button' %></li>
        </ul>
      </div>
    </header>

    <div class="record_table_wrapper">
      <table class="record_table">
        <thead>
          <tr>
            <th><%= column_title :transaction, :created_at %></th>
            <th><%= column_title :transaction, :category_id %></th>
            <th><%= column_title :transaction, :account_id %></th>
            <th><%= column_title :transaction, :payee %></th>
            <th class="text_right"><%= column_title :transaction, :amount %></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <%= render @transactions %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/transactions/new.html.erb
<div class="grid">
  <div class="unit content_body">
    <header class="grid record_table_title">
      <div class="unit section_title_container">
        <h1 class="section_title"><%= t('transaction.titles.new') %></h1>
      </div>
    </header>
    <%= render 'form', transaction: @transaction %>
  </div>
</div>